export const GETUSERS = "GETUSERS";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const DELETEUSER = "DELETEUSER";
export const DELETEUSER_SUCCESS = "DELETEUSER_SUCCESS";